apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-path: docker-registry/base
  name: docker-registry-kustomization
  namespace: docker-registry-kustomization-appsub
spec:
  channel: docker-registry-kustomization-channel/docker-registry-kustomization
  placement:
    placementRef:
      name: docker-registry-kustomization
      kind: PlacementRule
