apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: hugo-nginx
    apps.open-cluster-management.io/git-path:
    # "replace" is the default, alternative is "merge"
    apps.open-cluster-management.io/reconcile-option: replace
  labels:
    app: book-import
  name: book-import
spec:
  channel: book-import/book-import
  placement:
    placementRef:
      kind: PlacementRule
      name: book-import
