apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-toolbox
  namespace: my-git-deploy-target
spec:
  selector:
    matchLabels:
      app: openshift-toolbox
  template:
    metadata:
      labels:
        app: openshift-toolbox
    spec:
      containers:
      - image: quay.io/noseka1/openshift-toolbox:basic
        name: openshift-toolbox
